# Generated by Django 3.2.5 on 2024-05-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('Фрукты', 'Фрукты'), ('Овощи', 'Овощи'), ('Мясо', 'Мясо'), ('Рыба', 'Рыба'), ('Молочные продукты', 'Молочные продукты'), ('Зерновые и крупы', 'Зерновые и крупы'), ('Специи', 'Специи'), ('Масла и жиры', 'Масла и жиры')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default/default.jpg', upload_to='recipes/')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_recipes', to=settings.AUTH_USER_MODEL)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooked_recipes', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_dishes', to=settings.AUTH_USER_MODEL)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooked_dishes', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(to='api.Recipe')),
            ],
        ),
    ]
