# Generated by Django 3.2.5 on 2024-05-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
