# Generated by Django 3.2.5 on 2024-05-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_price',
        ),
    ]
