# Generated by Django 3.2.5 on 2024-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recipe_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
